Github Action script to run preview_namelists
ESCOMP/CESM pull request #305
Opened 2024-11-21 15:27 UTC by mnlevy1981

### Description of changes

Adds Github Action to create cases using a range of compsets (currently `B`, `C`, `C` with MARBL, `D`, `I`, `Q`, and `T`) and run `preview_namelists`. I intentionally set up the matrix to turn this into 35 parallel jobs (7 compsets and 5 versions of python)... it might be more efficient to have a separate job for each version of python that creates all 7 compsets in that same job, but I think that would make it harder to parse the results. If a `B` compset is failing because of issues in MOM6, CAM, and CLM, then we should see failures in `B`, both `C`s, `I`, and `Q` tests while a single job per python version would just abort after the first failure and not catch the other four.

### Specific notes

Contributors other than yourself, if any: @manishvenu was helpful in getting past some issues I had with github actions

Fixes: [Github issue #s] And brief description of each issue.

User interface changes?: [ No/Yes ]
[ If yes, describe what changed, and steps taken to ensure backward compatibility ]

Testing performed (automated tests and/or manual tests): These tests have run on my branch at https://github.com/mnlevy1981/cesm/actions/runs/11946703920 -- note that I had 3.14 in the python version matrix, but those tests failed with

```
Version 3.14 was not found in the local cache
  Error: The version '3.14' with architecture 'x64' was not found for Ubuntu 22.04.
```

So I removed it from this PR. Test results:

* Fails in python 3.9 for G and B compsets because CICE's `buildnml` relies on `glob.glob` API introduced in 3.10
* Fails all 3.12 and 3.13 tests because `distutils` has been removed from the standard library

2024-11-22 17:19 UTC, jedwards4b requested changes
@mnlevy1981 I believe that if you update to the latest cime it should fix the distutils issue.

2024-11-22 17:19 UTC, jedwards4b commented on .github/workflows/preview_namelist.yaml
> +        uses: actions/setup-python@v4
should be actions/setup-python@v5

2024-11-22 17:43 UTC, mnlevy1981 commented
> @mnlevy1981 I believe that if you update to the latest cime it should fix the distutils issue.

I'll leave that to Chris when he pushes the newest alpha tags to `cesm3.0-alphabranch` :) I did note on https://github.com/ESMCI/cime/issues/4668 that `master` still has a few `from distutils.spawn import find_executable`, but the failure I'm seeing in the current tests is from `from distutils import file_util` and those have been removed.

2024-11-22 19:21 UTC, mnlevy1981 commented on .github/workflows/preview_namelist.yaml
> +        uses: actions/setup-python@v4
done in c9eb302

2024-12-04 22:41 UTC, mnlevy1981 commented
Closed in favor of #307

2024-12-04 22:41 UTC, closed without merging